### ISSUE TITLE
How many GPUs does HistoGAN need for training？

### ISSUE THREAD

**Issue by Radium98** [mahmoudnafifi/HistoGAN#10]
Can you tell me your training configuration？Such how many GPUs you need for training and how long it takes for training?

**Comment by mahmoudnafifi** [comment]
All models used in the paper were trained using --network_capacity 16 due to the hardware limitation. You can try increasing this number for a better quality if your dataset is large enough. The training was on a single GPU. Typically it takes 3-5 days to show reasonable results, but it varies based on the target domain and the dataset size.
