### ISSUE TITLE
Runtime error: CUDA out of memory

### ISSUE THREAD

**Issue by Edison12300** [mahmoudnafifi/HistoGAN#23]
Hi, I've been trying to train your model with conda, but I keep run into an error saying that I don't have enough memory.
Are there any solutions to this error? I've looked online, but there doesn't seem to be a way to fix this.
I'm using CUDA 10.2 and pytorch 1.10.3.
![image](https://user-images.githubusercontent.com/71360570/162575542-ab025220-c590-46ee-b390-284f8206bef8.png)
Thanks!

**Comment by mahmoudnafifi** [comment]
That is either due to the network capacity or histogram computation. Try with a lower network capacity either by using lower image resolutions (`--image_size`) or reduce the entire network capacity from `--network_capacity`. To reduce memory use for histogram computations, you have several options: 1- reduce the maximum image size before computing the histogram feature (`--hist_insz`), 2- reduce histogram bins (`--hist_bin`), 3- or try another lighter histogram feature (e.g., rg-chromaticity) — this option wasn’t tested before but it may work on the same way of the uv-histogram feature. More details about histogram features implemented in this repo can be found [here](https://github.com/mahmoudnafifi/HistoGAN/tree/master/histogram_classes). Also check the colab example from the main page.

**Comment by Edison12300** [comment]
Thanks! Reducing network capacity and histogram bins helps.
It can run now. Thanks for the help!
